name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches: [main, master]
    tags: ["v*"]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Download Grype vulnerability database cache
        id: grype-db-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/grype/db
          key: grype-db-${{ runner.os }}-v1
          restore-keys: |
            grype-db-${{ runner.os }}-

      - name: Install Syft and Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM with Syft
        run: |
          syft ghcr.io/${{ github.repository }}:${{ env.DOCKER_METADATA_OUTPUT_VERSION }} -o json > sbom.json
          syft ghcr.io/${{ github.repository }}:${{ env.DOCKER_METADATA_OUTPUT_VERSION }} -o cyclonedx > sbom.cdx.json

      - name: Scan image with Grype (JSON)
        run: |
          grype ghcr.io/${{ github.repository }}:${{ env.DOCKER_METADATA_OUTPUT_VERSION }} -o json > grype-report.json

      - name: Scan image with Grype (HTML)
        run: |
          mkdir -p ~/.grype/templates
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/templates/html.tmpl -o ~/.grype/templates/html.tmpl
          grype ghcr.io/${{ github.repository }}:${{ env.DOCKER_METADATA_OUTPUT_VERSION }} -o template -t ~/.grype/templates/html.tmpl > grype-report.html

      - name: Upload SBOM and vulnerability reports as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-and-vulnerability-reports
          path: |
            sbom.json
            sbom.cdx.json
            grype-report.json
            grype-report.html
